# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=150)),
                ('archival_active', models.BooleanField()),
                ('first_registered', models.DateTimeField()),
                ('last_altered', models.DateTimeField()),
            ],
        ),
    ]
