# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputWaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_flow', models.FloatField()),
                ('input_temp', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KlystronBodyWaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_flow', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KlystronCollectorWaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_flow', models.FloatField()),
                ('collector_temp', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KlystronSolenoidWaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solenoid_flow', models.FloatField()),
                ('solenoid_temp', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModOilTankWaterSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_flow', models.FloatField()),
                ('tank_temp', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
