# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0003_inputwatersystem_klystronbodywatersystem_klystroncollectorwatersystem_klystronsolenoidwatersystem_mo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputwatersystem',
            name='input_flow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='klystronbodywatersystem',
            name='body_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='klystroncollectorwatersystem',
            name='collector_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='klystronsolenoidwatersystem',
            name='solenoid_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='modoiltankwatersystem',
            name='tank_temp',
            field=models.FloatField(null=True),
        ),
    ]
