# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_auto_20170205_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStandEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.FloatField()),
                ('light_averaged', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
