# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0006_rfpowermeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArchiveSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=150)),
                ('sampleCapture', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
